# Generated by Django 3.2.7 on 2021-10-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('degree', models.TextField(max_length=500)),
                ('inter', models.TextField(max_length=500)),
                ('highschool', models.TextField(max_length=500)),
                ('about_you', models.TextField(max_length=1000)),
                ('skills', models.TextField(max_length=1000)),
                ('experience', models.TextField(max_length=1000)),
            ],
        ),
    ]
