# Generated by Django 3.2.7 on 2021-10-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_resume_cv_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='cv_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
